### ISSUE TITLE
Timeout Exceptions

### ISSUE THREAD

**Issue by debuggerUA** [levelup/Android-HttpClient#6]
Hi, in past several weeks I have many users complaining about bad networking experience.
Managed to get logs and here is what I have.
Tried to extend timeout to 30 seconds and it didn't helped.
```
exception during loading
    HttpTimeoutException http:-1 req:HttpTwitterRequest{16c5486b https://api.twitter.com/1.1/statuses/mentions_timeline.json?include_entities=true&contributor_details=false&trim_user=false&include_rts=true&count=200&since_id=569566499867901951 for Account:Twi:debuggerUA:Denis Babak} Timeout error null
            at co.tophe.HttpTimeoutException$Builder.build(HttpTimeoutException.java:21)
            at co.tophe.HttpTimeoutException$Builder.build(HttpTimeoutException.java:14)
            at co.tophe.ion.HttpEngineIon.queryResponse(HttpEngineIon.java:176)
            at co.tophe.ion.HttpEngineIon.queryResponse(HttpEngineIon.java:67)
            at co.tophe.AbstractHttpEngine.call(AbstractHttpEngine.java:175)
            at com.plume.twitter.TwitterClient.doTwitterRequest(TwitterClient.java:1175)
            at com.plume.twitter.TwitterClient.getMentions(TwitterClient.java:803)
            at com.levelup.socialapi.twitter.UpdateTwitterMentions$1.loadPage(UpdateTwitterMentions.java:21)
            at com.levelup.socialapi.twitter.UpdateTwitterMentions$1.loadPage(UpdateTwitterMentions.java:18)
            at com.levelup.socialapi.AbstractPageLoader.loadAllNeededPages(AbstractPageLoader.java:19)
            at com.levelup.socialapi.twitter.UpdateThreadTwitter.runUpdate(UpdateThreadTwitter.java:59)
            at com.levelup.socialapi.UpdateThread.call(UpdateThread.java:68)
            at com.levelup.socialapi.UpdateThread.call(UpdateThread.java:10)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at co.tophe.async.AsyncTask.run(AsyncTask.java:116)
            at com.levelup.socialapi.UpdateThreadFuture.run(UpdateThreadFuture.java:34)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by robUx4** [comment]
You may try to use a custom executor with less threads for the network calls. It helped in another app.

Also make sure you have the latest Ion, it could be a HTTP/2 issue that is already fixed.
